//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SaglikMerkeziEntities : DbContext
    {
        public DB_SaglikMerkeziEntities()
            : base("name=DB_SaglikMerkeziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Adres> tbl_Adres { get; set; }
        public virtual DbSet<tbl_Anasayfa> tbl_Anasayfa { get; set; }
        public virtual DbSet<tbl_AsiTakvimi> tbl_AsiTakvimi { get; set; }
        public virtual DbSet<tbl_Cinsiyet> tbl_Cinsiyet { get; set; }
        public virtual DbSet<tbl_Galeri> tbl_Galeri { get; set; }
        public virtual DbSet<tbl_Hekim> tbl_Hekim { get; set; }
        public virtual DbSet<tbl_Hemsire> tbl_Hemsire { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_Linkler> tbl_Linkler { get; set; }
        public virtual DbSet<tbl_MesaiCizelge> tbl_MesaiCizelge { get; set; }
    }
}
