//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anasayfa
    {
        public int AnasayfaID { get; set; }
        public string AnasayfaFoto { get; set; }
        public string Aciklama { get; set; }
    }
}
