//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hekim
    {
        public int HekimID { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        public Nullable<int> HemsireID { get; set; }
        public string HekimAdSoyad { get; set; }
        public string Unvan { get; set; }
        public string HekimNo { get; set; }
        public string HekimFoto { get; set; }
    }
}
