//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MesaiCizelge
    {
        public int CizelgeID { get; set; }
        public string CizelgeAd { get; set; }
        public string CizelgeFoto { get; set; }
    }
}
